### ISSUE TITLE
usergroups.list

### ISSUE THREAD

**Issue by rickt** [bluele/slack#14]
(apologies in advanced for the unorthodox message to you, i have never done a pull request before #noob). 

i forked bluele/slack some time ago so i could get some backend apps up in google appengine. i added usergroups.go (https://github.com/rickt/slack-appengine/blob/master/usergroups.go) to my own repo that implements the usergroups.list Slack API method. 

unfortunately i don't know how to do a pull request for a single file. i don't think a full pull request with all my changes would be appropriate because i had to change slack.go to be "appengine aware" (https://github.com/rickt/slack-appengine/commit/f66cbd55e5d08ca2b7e429d1b08028e2e7bb286a) and i don't think it makes sense for that to be in your repo at all.

anyway, i thought you might appreciate the usergroups.go and because im a github noob i had no idea how to get it to you the proper way. hope you don't mind me using an "issue" to send it over to you. 

thanks for writing such a great codebase to build on! :thumbsup: :-D

-RMT

**Comment by bluele** [comment]
Thanks. I'll add a support for usergroups api, so use it as a reference.
