### ISSUE TITLE
ChatPostMessage is broken

### ISSUE THREAD

**Issue by EmielM** [bluele/slack#24]
I mean, what could one possibly expect from a client for a messaging service?

All messages containing a `&` fail (text after `&` is missing), because the actual text is not properly encoded at https://github.com/bluele/slack/blob/master/chat.go#L54.

A simple solution would escape with `url.QueryEscape()`, a more elegant one probably using `url.Values`.

**Comment by bluele** [comment]
Thank you for your report.
I'll check this issue on this weekend.
